name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: npm install
        env:
          CI: true
        run:
          npm install
      - name: zip
        run:
          zip -r deploy.zip ./*
      - name: deploy
        run:
          aws lambda update-function-code --function-name=kakao_bot --zip-file=fileb://deploy.zip